version = 3.9.10
runner.dialect = scala3
maxColumn = 100
align.preset = most
rewrite.rules = [RedundantBraces, SortModifiers]
docstrings.style = Asterisk
docstrings.wrap = yes
newlines.source = fold
project.git = true
project.excludeFilters = ["target/.*"]
